version: '2'
services:
  amule:
    container_name: amule
    image: tetreum/amule
    ports:
      ## web server port
      - "4711:4711"
      - "4712:4712"
      - "4662:4662"
      - "4672:4672/udp"
    environment:
      - PUID=1000
      - GUID=1000
      ## Set the password that you want for accessing the ui
      - WEBUI_PWD=c0mpl3x_p4ssw0rd
      ## template can be default or AmuleWebUI-Reloaded
      - WEBUI_TEMPLATE=AmuleWebUI-Reloaded
      ## Folders that you want to share recursively
      ## you can set multiple folders using a comma separated list
      ## Example: -SHARED_FOLDERS=/incoming,/storage/movies,/yotube/shows
      -SHARED_FOLDERS=/incoming
    networks:
      amule:
        aliases:
          - amule
    volumes:
      - /conf:/home/amule/.aMule
      - /data:/incoming
      - /tmp:/temp
networks:
  amule:

