version: '2'
services:
  amule:
    image: tetreum/amule
    ports:
      ## web server port
      - "4711:4711"
      - "4712:4712"
      - "4662:4662"
      - "4672:4672/udp"
    environment:
      - PUID=1000
      - GUID=1000
      - WEBUI_PWD=c0mpl3x_p4ssw0rd
    networks:
      amule:
        aliases:
          - amule
    volumes:
      - /conf:/home/amule/.aMule
      - /data:/incoming
      - /tmp:/temp
networks:
  amule:

